url: "http://aiderplusloin.solidarites.org"
name: Aider plus loin - SOLIDARITÉS INTERNATIONAL
title: Aider plus loin - SOLIDARITÉS INTERNATIONAL
logo: "http://www.adfinitas.fr/wp-content/themes/adfinitas/images/logo-adfinitas.png"
paginate: 3
paginate_path: "/page:num"
permalink: "/article/:title"
encoding: UTF-8
woopra_id: solidarites.org
google_analytics_id: UA-15931825-1
url_iraiser: "https://dons.solidarites.org"
collections:
  ebola_blog_FR:
    output: false
    permalink: "/ebola/blog/article/:title/"
  ebola_blog_EN:
    output: false
    permalink: "/ebola/en/blog/post/:title/"
defaults:
  - scope:
      path: ""
      type: ebola_blog_FR
    values:
      layout: blog_post_FR
  - scope:
      path: ""
      type: ebola_blog_EN
    values:
      layout: blog_post_EN
