url: "http://aiderplusloin.solidarites.org"
name: Aider plus loin - SOLIDARITÉS INTERNATIONAL
title: Aider plus loin - SOLIDARITÉS INTERNATIONAL
logo: "http://www.adfinitas.fr/wp-content/themes/adfinitas/images/logo-adfinitas.png"
paginate: 3
paginate_path: "/ebola/blog/list/page:num"
permalink: "/article/:title"
encoding: UTF-8
woopra_id: solidarites.org
google_analytics_id: UA-15931825-1
url_iraiser: "https://dons.solidarites.org"
collections:
  ebola_blog_fr:
    output: true
    permalink: "/ebola/blog/article/:title.html"
  ebola_blog_en:
    output: true
    permalink: "/ebola/en/blog/post/:title.html"
