url: "http://aiderplusloin.solidarites.org"
name: Aider plus loin - SOLIDARITÉS INTERNATIONAL
title: Aider plus loin - SOLIDARITÉS INTERNATIONAL
logo: "http://www.adfinitas.fr/wp-content/themes/adfinitas/images/logo-adfinitas.png"
paginate: 10
paginate_path: "/ebola/blog/list/page:num"
permalink: "/article/:title"
encoding: UTF-8
woopra_id: solidarites.org
google_analytics_id: UA-15931825-1
author: "SOLIDARITÉS INTERNATIONAL"
url_iraiser: "https://dons.solidarites.org"
collections:
  ebola_blog_fr:
    output: true
    permalink: "/ebola/blog/article/:title.html"
  ebola_blog_en:
    output: true
    permalink: "/ebola/en/blog/article/:title.html"
defaults:
- scope:
    path: ""
    type: "ebola_blog_fr"
  values:
    layout: blog_post_fr
- scope:
    path: ""
    type: "ebola_blog_en"
  values:
    layout: blog_post_en
